# Site default meta keywords
#keywords: site, wide, default, keywords

# path to bootstrap css template if not specified,
# uses full bootstrap-combined.min.css
#
# These free themes are provided by my firends at http://bootstrapcdn.com
#
#bootstrap_css: //netdna.bootstrapcdn.com/bootswatch/3.0.0/amelia/bootstrap.min.css
#bootstrap_css: //netdna.bootstrapcdn.com/bootswatch/3.0.0/cerulean/bootstrap.min.css
#bootstrap_css: //netdna.bootstrapcdn.com/bootswatch/3.0.0/cosmo/bootstrap.min.css
#bootstrap_css: //netdna.bootstrapcdn.com/bootswatch/3.0.0/cyborg/bootstrap.min.css
#bootstrap_css: //netdna.bootstrapcdn.com/bootswatch/3.0.0/flatly/bootstrap.min.css
#bootstrap_css: //netdna.bootstrapcdn.com/bootswatch/3.0.0/journal/bootstrap.min.css
#bootstrap_css: //netdna.bootstrapcdn.com/bootswatch/3.0.0/readable/bootstrap.min.css
#bootstrap_css: //netdna.bootstrapcdn.com/bootswatch/3.0.0/simplex/bootstrap.min.css
bootstrap_css: //netdna.bootstrapcdn.com/bootswatch/3.0.0/slate/bootstrap.min.css
#bootstrap_css: //netdna.bootstrapcdn.com/bootswatch/3.0.0/spacelab/bootstrap.min.css
#bootstrap_css: //netdna.bootstrapcdn.com/bootswatch/3.0.0/united/bootstrap.min.css

# highlight.js is the code highlighter in this theme
# choose a highlight.js theme here or delete all to disable
# - for demos see: http://softwaremaniacs.org/media/soft/highlight/test.html
#
# highlightjs: github # << default
# highlightjs: arta
# highlightjs: ascetic
# highlightjs: brown_paper
# highlightjs: dark
# highlightjs: default
# highlightjs: docco
# highlightjs: far
# highlightjs: foundation
# highlightjs: googlecode
# highlightjs: idea
# highlightjs: ir_black
# highlightjs: magula
# highlightjs: mono-blue
# highlightjs: monokai
# highlightjs: monokai_sublime
# highlightjs: obsidian
# highlightjs: pojoaque
# highlightjs: railscasts
# highlightjs: rainbow
# highlightjs: school_book
# highlightjs: school_book.png
# highlightjs: solarized_dark
# highlightjs: solarized_light
# highlightjs: sunburst
# highlightjs: tomorrow
# highlightjs: tomorrow-night-blue
# highlightjs: tomorrow-night-bright
# highlightjs: tomorrow-night
# highlightjs: tomorrow-night-eighties
# highlightjs: vs
# highlightjs: xcode
# highlightjs: zenburn

# inverse bootstrap navbar
#bs_nav_inverse: true

# This section turns on javascript components,
# they're off by default to make things faster.
#bootstrap_js: true
#imagesloaded_js: true # gives images a loading icon
#fancybox: true

# stick footer to page bottom
sticky_footer: true

# don't use this without sticky_footer
#footer_color: 'black'

# Include gravatar to left of page title in navbar.
# It will overflow navbar a bit intentionally.
#
# NOTE: this should be considered experimental
gravatar:
  # e.g.
  #gravatar: ed808193b8c2c8516715816f90a005b2 # that's me

menu:
  Home: /
  About: /about
  Archives: /archives

widgets:
- search
- category
- tagcloud
#- recent_posts
#- tag

# For use with tagcloud or tag widgets
# - only tags >= to tag_minium are shown
tag_minium: 3

excerpt_link: read more

twitter_id:
facebook_id:
linkedin_id:
github_id:

addthis:
  enable: true
  pubid:
  twitter: true
  facebook: true

google_analytics:
rss:

disqus_shortname:

